"""Initial: had to run the script again to create tables

Revision ID: 8cb1a4b9d540
Revises: 
Create Date: 2020-09-30 04:11:35.685669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb1a4b9d540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('descr', sa.String(length=130), nullable=True),
    sa.Column('enforce', sa.Boolean(), nullable=False),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acct_bal', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.String(length=160), nullable=True),
    sa.Column('organisation_name2', sa.String(length=160), nullable=True),
    sa.Column('organisation_address', sa.String(length=160), nullable=True),
    sa.Column('organisation_address2', sa.String(length=160), nullable=True),
    sa.Column('organisation_phone', sa.String(length=160), nullable=True),
    sa.Column('organisation_email', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('midname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=False),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('datejoined', sa.DateTime(), nullable=True),
    sa.Column('cmono', sa.String(length=15), nullable=True),
    sa.Column('state_of_origin', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_cmono'), 'members', ['cmono'], unique=False)
    op.create_index(op.f('ix_members_firstname'), 'members', ['firstname'], unique=False)
    op.create_index(op.f('ix_members_lastname'), 'members', ['lastname'], unique=False)
    op.create_index(op.f('ix_members_midname'), 'members', ['midname'], unique=False)
    op.create_index(op.f('ix_members_state_of_origin'), 'members', ['state_of_origin'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('excos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('office', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excos_member_id'), 'excos', ['member_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('mode_of_payment', sa.String(length=100), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('monthly_dues', sa.Integer(), nullable=True),
    sa.Column('annual_dues', sa.Integer(), nullable=True),
    sa.Column('harvest_levy', sa.Integer(), nullable=True),
    sa.Column('life_policy', sa.Integer(), nullable=True),
    sa.Column('others', sa.Integer(), nullable=True),
    sa.Column('total_pay', sa.Integer(), nullable=True),
    sa.Column('paid_to_date', sa.Integer(), nullable=True),
    sa.Column('outstanding_bal', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_account')
    op.drop_table('payments')
    op.drop_index(op.f('ix_excos_member_id'), table_name='excos')
    op.drop_table('excos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_members_state_of_origin'), table_name='members')
    op.drop_index(op.f('ix_members_midname'), table_name='members')
    op.drop_index(op.f('ix_members_lastname'), table_name='members')
    op.drop_index(op.f('ix_members_firstname'), table_name='members')
    op.drop_index(op.f('ix_members_cmono'), table_name='members')
    op.drop_table('members')
    op.drop_table('global_setup')
    op.drop_table('general_account')
    op.drop_table('finance_setup')
    # ### end Alembic commands ###
